apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pqc-dev

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml
- configmap-patch.yaml

replicas:
- name: pqc-secure-transfer
  count: 1

images:
- name: pqc-secure-transfer
  newTag: dev